version: "3.8"

services:
  django:
    build: ./Infrastructure/python
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src/app/code
    volumes:
      - ./Application/core:/usr/src/app/code
      - ./Infrastructure/python/work/requirements.txt:/usr/src/app/requirements.txt
      - ./.env:/usr/src/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    expose:
      - "5432"
    env_file:
      - "./.env"
